version: '3.7'

services:
    crm_back:
        build: ./
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        env_file: 
            - ./.env
    crm_db:
        image: postgres:12.0-alpine
        volumes:
            - crm_postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=tof
            - POSTGRES_PASSWORD=1
            - POSTGRES_DB=crm_back

volumes:
    crm_postgres_data:
     
    