# Generated by Django 3.1 on 2021-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_choice',
            field=models.CharField(choices=[('cash', 'Наличные'), ('elsom', 'Эльсом'), ('card', 'Карта')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(choices=[('study', 'Оплата за обучение'), ('penalty', 'Оплата за пеню')], max_length=50),
        ),
    ]
