# Generated by Django 3.1 on 2021-05-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('FullStack', 'FullStack'), ('JavaScriptEvening', 'JavaScriptEvening'), ('PythonEvening', 'PythonEvening')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('last_check', models.DateField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='group.course')),
            ],
        ),
    ]
