# Generated by Django 3.1 on 2021-06-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('FullStack', 'FullStack'), ('JavaScriptEvening', 'JavaScriptEvening'), ('PythonEvening', 'PythonEvening')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month_1', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_4', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_5', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_7', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_8', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_9', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_10', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_11', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_month_12', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('last_check', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='group.course')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
