# Generated by Django 3.1 on 2021-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('FullStack', 'FullStack'), ('JavaScriptEvening', 'JavaScriptEvening'), ('PythonEvening', 'PythonEvening'), ('freeze', 'Замороженные студенты')], max_length=50),
        ),
    ]
