# Generated by Django 3.1 on 2021-06-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20210604_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created']},
        ),
    ]
