# Generated by Django 3.1 on 2021-06-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_paymentmonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMonth',
        ),
    ]
