# Generated by Django 3.1 on 2021-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210602_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_month',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
