# Generated by Django 3.1 on 2021-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210603_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
