# Generated by Django 3.1 on 2021-06-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210603_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='updated',
            new_name='freeze_date',
        ),
    ]
