# Generated by Django 3.1 on 2021-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210603_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AddField(
            model_name='student',
            name='freeze_status',
            field=models.BooleanField(default=False),
        ),
    ]
