# Generated by Django 3.1 on 2021-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210603_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='student',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
