# Generated by Django 3.1 on 2021-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210604_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duration_check',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
