# Generated by Django 3.1 on 2021-06-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_duration_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='penalty_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='penalty_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_data',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
