# Generated by Django 3.1 on 2021-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_penalty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
