# Generated by Django 3.1 on 2021-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_delete_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='penalty_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='penalty_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
