# Generated by Django 3.1 on 2021-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20210607_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_data',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
