# Generated by Django 3.1 on 2021-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20210614_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_month_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_11',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_month_9',
        ),
        migrations.AddField(
            model_name='student',
            name='data_payment',
            field=models.JSONField(default={}),
        ),
    ]
