# Generated by Django 3.1 on 2021-06-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20210614_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='data_payment',
        ),
    ]
